---
title: "IRES microclimate met data"
author: "Heather Throop"
format: html
editor: visual
editor_options: 
  chunk_output_type: console
---

## Overview

This file works up met station data from the 2022 IRES Microclimate project, microphases 1 and 2. Original data were downloaded from the SASSCAL website.

File written: 22 July 2025, Heather Throop\
Last update:

## Preparation Steps

```{r}
#| echo: false
#| label: load packages 

library(here) # v. 0.1
library(stringr) # v. 1.2.0
library(purrr) # v. 0.2.3
library(tidyverse)
library(lubridate)
library(ggtext)


# Read in the moon and sun images as grobs
moon_img <- rasterGrob(readPNG("moon.png"), interpolate = TRUE)
sun_img <- rasterGrob(readPNG("sun.png"), interpolate = TRUE)
```

## Microphase 1

### Met Data Load and Prep

```{r}
#| label: pull in met station data

#--read and work up data for microphase 1-----------
weather_phase1_df = read.csv(here("data", "microphase1_gobabebmet.csv"),header=TRUE)

weather_phase1_df <- weather_phase1_df |>
  mutate(Datetime = as.POSIXct(Datetime, 
                               format = "%m/%d/%y %H:%M", tz = "Africa/Johannesburg"))

# Define the experiment start time in Johannesburg time zone
start_time_m1 <- as.POSIXct("2022-07-24 11:00:00", tz = "Africa/Johannesburg")

# Compute elapsed time in hours
weather_phase1_df <- weather_phase1_df |>
  mutate(elapsed_time = as.numeric(difftime(Datetime, start_time_m1, units = "hours")))

# define night (6 pm to 6 am) periods during the experiment
night1_start_m1 <- 7
night1_end_m1 <- 19
night2_start_m1 <- 31
night2_end_m1 <- 43

```

### Plot Data

```{r}
#| label: fog and humidity plot (Fig 2A)

coeff <- 100

fog_humidity_m1_p1 <- weather_phase1_df |>
  ggplot(aes(x=elapsed_time)) +
  geom_bar(aes(y=Fog), stat = "identity", fill='black') +
  geom_line(aes(y=Humidity / coeff), color = "#1b98e0") +
  geom_area(aes(y=Humidity / coeff), fill = "#1b98e0", alpha=0.2) +
  ylim(0,1) +
  scale_y_continuous(name = "Fog (mm)", 
                     sec.axis = sec_axis(~.*coeff, name="Humidity (%)"),expand=c(0,0)) +
  xlab("Elapsed Time (hours)") + 
  ylab("Fog (mm)") +
  # Add "A." in upper-left corner
  annotate("text", x = 0, y = Inf, label = "A.", hjust = -0.5, 
           vjust = 1.5, size = 6) +
  theme_bw() +
  theme(text = element_text(size = 15)) +
  theme(panel.grid.major = element_blank()) +
  theme(panel.grid.minor = element_blank()) +
  theme(axis.text.x = element_text(vjust = 0.5)) +
  scale_x_continuous(limits = c(0, 48), expand = c(0,0))
fog_humidity_m1_p1

# save the plot
ggsave(filename = 
       here("output","figures", "Fig2A_microphase1_fog_humidity_plot.jpg"),
       device = "jpeg",
       width = 8, height = 6, dpi = 300)
```

```{r}
#| label: air temperature plot

airtemp_m1_p1 <- weather_phase1_df |>
  ggplot(aes(x = elapsed_time)) +
  # Add shaded night areas
  annotate("rect", xmin = night1_start_m1, xmax = night1_end_m1, 
           ymin = -Inf, ymax = Inf, alpha = 0.2, fill = "grey") +
  annotate("rect", xmin = night2_start_m1, xmax = night2_end_m1, 
           ymin = -Inf, ymax = Inf, alpha = 0.2, fill = "grey") +
  
  # Add soil temperature line
  geom_line(aes(y = AirTemperature)) +

  # Add moon images
  annotation_custom(moon_img, xmin = 10, xmax = 16, ymin = 26, ymax = 32) +
  annotation_custom(moon_img, xmin = 34, xmax = 40, ymin = 26, ymax = 32) +

  # Add sun images in day areas
  annotation_custom(sun_img, xmin = 22, xmax = 28, ymin = 26, ymax = 32) +
 # annotation_custom(sun_img, xmin = 39, xmax = 41, ymin = 30, ymax = 36) +

  # Plot formatting
  xlab("Elapsed Time (h)") + 
  ylab("Air Temperature (C)") +
  theme_bw() +
  theme(text = element_text(size = 15),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank()) +
  scale_x_continuous(limits = c(0, 48))

airtemp_m1_p1

# save the plot
ggsave(filename = 
       here("output","figures", "microphase1_airtemp_plot.jpg"),
       device = "jpeg",
       width = 8, height = 6, dpi = 300)
```

```{r}
#| label: soil temperature plot

soiltemp_m1_p1 <- weather_phase1_df |>
  ggplot(aes(x = elapsed_time)) +
  # Add shaded night areas
  annotate("rect", xmin = night1_start_m1, xmax = night1_end_m1, 
           ymin = -Inf, ymax = Inf, alpha = 0.2, fill = "grey") +
  annotate("rect", xmin = night2_start_m1, xmax = night2_end_m1, 
           ymin = -Inf, ymax = Inf, alpha = 0.2, fill = "grey") +
  
  # Add soil temperature line
  geom_line(aes(y = SoilTemp)) +
  geom_line(aes(y = AirTemperature)) +

  # Add moon images
  annotation_custom(moon_img, xmin = 10, xmax = 16, ymin = 30, ymax = 36) +
  annotation_custom(moon_img, xmin = 34, xmax = 40, ymin = 30, ymax = 36) +

  # Add sun images in day areas
  annotation_custom(sun_img, xmin = 22, xmax = 28, ymin = 30, ymax = 36) +
 # annotation_custom(sun_img, xmin = 39, xmax = 41, ymin = 30, ymax = 36) +

  # Plot formatting
  xlab("Elapsed Time (h)") + 
  ylab("Soil Temperature (C)") +
  theme_bw() +
  theme(text = element_text(size = 15),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank()) +
  scale_x_continuous(limits = c(0, 48))

soiltemp_m1_p1

# save the plot
ggsave(filename = 
       here("output","figures", "microphase1_soiltemp_plot.jpg"),
       device = "jpeg",
       width = 8, height = 6, dpi = 300)

```

```{r}
#| label: soil+air temperature plot (Fig. 2B)

soil_and_air_temp_m1_p1 <- weather_phase1_df |>
  ggplot(aes(x = elapsed_time)) +
  # Add shaded night areas
  annotate("rect", xmin = night1_start_m1, xmax = night1_end_m1, 
           ymin = -Inf, ymax = Inf, alpha = 0.2, fill = "grey") +
  annotate("rect", xmin = night2_start_m1, xmax = night2_end_m1, 
           ymin = -Inf, ymax = Inf, alpha = 0.2, fill = "grey") +
  
  # Add soil temperature (brown dashed) and air temperature (blue solid) lines
  geom_line(aes(y = SoilTemp, color = "Soil Temperature"), 
            linetype = "dashed", linewidth = 1) +
  geom_line(aes(y = AirTemperature, color = "Air Temperature"), linewidth = 1) +
  # Add moon images
  annotation_custom(moon_img, xmin = 11, xmax = 15, ymin = 30, ymax = 34) +
  annotation_custom(moon_img, xmin = 35, xmax = 39, ymin = 30, ymax = 34) +

  # Add sun images in day areas
  annotation_custom(sun_img, xmin = 23, xmax = 27, ymin = 30, ymax = 34) +
 # annotation_custom(sun_img, xmin = 39, xmax = 41, ymin = 30, ymax = 36) +

  # Add "B." in upper-left corner
  annotate("text", x = 0, y = Inf, label = "B.", hjust = -0.5, 
           vjust = 1.5, size = 6) +

  # Axes and scales
  scale_color_manual(values = c("Soil Temperature" = "#6e4424", "Air Temperature" = "blue")) +
  scale_x_continuous(limits = c(0, 48), expand = c(0, 0)) +
  scale_y_continuous(limits = c(5, 35), expand = c(0, 0)) +
  xlab("Elapsed Time (hours)") + 
  ylab("Temperature (°C)") +
  
  # Theme tweaks
  theme_bw() +
  theme(
    text = element_text(size = 15),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    legend.position = c(0.85, 0.70),
    legend.justification = c("right", "top"),
    legend.background = element_blank(),
    legend.key = element_blank(),
    legend.title = element_blank(),
    legend.text = element_text(size = 12)
  )

soil_and_air_temp_m1_p1

# save the plot
ggsave(filename = 
       here("output","figures", "Fig2B_microphase1_soil_and_air_temp_plot.jpg"),
       device = "jpeg",
       width = 8, height = 6, dpi = 300)
```

```{r}
#| label: Combine plots (FIG 2)


# supress legends in plot 2, use plot 1 legends for combined plot
plotA <- fog_humidity_m1_p1 + theme(legend.position = "none")
plotB <- soil_and_air_temp_m1_p1 + theme(legend.position = c(0.92, 0.75))

combined_plots <- plot_grid(plotA, plotB, ncol = 1, align = "v", rel_heights = c(1, 1))

final_plot <- ggdraw() +
  draw_plot(combined_plots, x = 0, y = 0, width = 1, height = 1)
final_plot

# save the plot
ggsave(filename = 
       here("output","figures", "Fig2_microphase1_weather.jpg"),
       device = "jpeg",
       width = 8, height = 6, dpi = 300)
```

## Microphase 2

### Met Data Load and Prep

```{r}
#| label: pull in met station data

#--read and work up data for microphase 1-----------
weather_phase2_df = read.csv(here("data", "microphase2_gobabeb-auss.csv"),header=TRUE)

weather_phase2_df$Station <- as.factor(weather_phase2_df$Station)

weather_phase2_df <- weather_phase2_df |>
  mutate(Datetime = as.POSIXct(Datetime, 
                               format = "%m/%d/%y %H:%M", tz = "Africa/Johannesburg"))

# Define the experiment start time in Johannesburg time zone
start_time_m2 <- as.POSIXct("2022-07-30 12:00:00", tz = "Africa/Johannesburg")

# Compute elapsed time in hours
weather_phase2_df <- weather_phase2_df |>
  mutate(elapsed_time = as.numeric(difftime(Datetime, start_time_m2, units = "hours")))

# define night (6 pm to 6 am) periods during the experiment - this is relative to elapsed time
night1_start_m2 <- 6
night1_end_m2 <- 18
night2_start_m2 <- 30
night2_end_m2 <- 42
```

### Gobabeeb Versus Aussininaus Data

```{r}
#| label: gobabeb vs aussininas humidity

humidity_site_comparison_m2_p1 <- weather_phase2_df |>
  ggplot(aes(x=elapsed_time)) +
  geom_line(aes(y=Humidity, color = Station)) +
  xlab("Elapsed Time (h)") + 
  ylab("Fog (mm)") +
  theme_bw() +
  theme(text = element_text(size = 15)) +
  theme(panel.grid.major = element_blank()) +
  theme(panel.grid.minor = element_blank()) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) 
humidity_site_comparison_m2_p1

```

```{r}
#| label: gobabeb vs aussininas fog

humidity_site_comparison_m2_p1 <- weather_phase2_df |>
  ggplot(aes(x=elapsed_time)) +
  geom_line(aes(y=Fog, color = Station)) +
  xlab("Elapsed Time (h)") + 
  ylab("Fog (mm)") +
  theme_bw() +
  theme(text = element_text(size = 15)) +
  theme(panel.grid.major = element_blank()) +
  theme(panel.grid.minor = element_blank()) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) 
humidity_site_comparison_m2_p1
```

```{r}
#| label: replace missing Gobabeb data with Aussinanis data

weather_phase2_gob_df <- weather_phase2_df |>
  drop_na() |>
  group_by(Datetime) |>
  filter(Station != "Aussinanis" | !any(Station == "Gobabeb")) |>
  ungroup()

```

### Plot Data

```{r}
#| label: fog and humidity plot (Fig 4A)

fog_humidity_m2_p1 <- weather_phase2_gob_df |>
  ggplot(aes(x=elapsed_time)) +
  geom_bar(aes(y=Fog), stat = "identity", fill='black') +
  geom_line(aes(y=Humidity / coeff), color = "#1b98e0") +
  geom_area(aes(y=Humidity / coeff), fill = "#1b98e0", alpha=0.2) +
  ylim(0,2) +
  scale_y_continuous(name = "Fog (mm)", 
                     sec.axis = sec_axis(~.*coeff, name="Humidity (%)"),expand=c(0,0)) +
  # Add "A." in upper-left corner
  annotate("text", x = 0, y = Inf, label = "A.", hjust = -0.5, 
           vjust = 1.5, size = 6) +
  xlab("Elapsed Time (hours)") + 
  ylab("Fog (mm)") +
  theme_bw() +
  theme(text = element_text(size = 15)) +
  theme(panel.grid.major = element_blank()) +
  theme(panel.grid.minor = element_blank()) +
  theme(axis.text.x = element_text(hjust=1)) +
  scale_x_continuous(limits = c(0, 48), expand=c(0,0))
fog_humidity_m2_p1

# save the plot
ggsave(filename = 
       here("output","figures", "Fig4A_microphase2_fog_humidity_plot.jpg"),
       device = "jpeg",
       width = 8, height = 6, dpi = 300)
```

```{r}
#| label: air temperature plot

airtemp_m2_p1 <- weather_phase2_gob_df |>
  ggplot(aes(x = elapsed_time)) +
  # Add shaded night areas
  annotate("rect", xmin = night1_start_m2, xmax = night1_end_m2, 
           ymin = -Inf, ymax = Inf, alpha = 0.2, fill = "grey") +
  annotate("rect", xmin = night2_start_m2, xmax = night2_end_m2, 
           ymin = -Inf, ymax = Inf, alpha = 0.2, fill = "grey") +
  
  # Add air temperature line
  geom_line(aes(y = AirTemp)) +

  # Add moon images
  annotation_custom(moon_img, xmin = 10, xmax = 15, ymin = 19, ymax = 24) +
  annotation_custom(moon_img, xmin = 34, xmax = 39, ymin = 19, ymax = 24) +
  
  # Add sun images in day areas
  annotation_custom(sun_img, xmin = 21, xmax = 26, ymin = 19, ymax = 24) +

  # Plot formatting
  xlab("Elapsed Time (h)") + 
  ylab("Air Temperature (C)") +
  theme_bw() +
  theme(text = element_text(size = 15),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank()) +
  scale_x_continuous(limits = c(0, 48))

airtemp_m2_p1

# save the plot
ggsave(filename = 
       here("output","figures", "microphase2_airtemp_plot.jpg"),
       device = "jpeg",
       width = 8, height = 6, dpi = 300)
```

```{r}
#| label: soil temperature plot

soiltemp_m2_p1 <- weather_phase2_gob_df |>
  ggplot(aes(x = elapsed_time)) +
  # Add shaded night areas
  annotate("rect", xmin = night1_start_m2, xmax = night1_end_m2, 
           ymin = -Inf, ymax = Inf, alpha = 0.2, fill = "grey") +
  annotate("rect", xmin = night2_start_m2, xmax = night2_end_m2, 
           ymin = -Inf, ymax = Inf, alpha = 0.2, fill = "grey") +
  
  # Add soil temperature line
  geom_line(aes(y = SoilTemp)) +

  # Add moon images
  annotation_custom(moon_img, xmin = 10, xmax = 15, ymin = 24, ymax = 29) +
  annotation_custom(moon_img, xmin = 34, xmax = 39, ymin = 24, ymax = 29) +

  # Add sun images in day areas
  annotation_custom(sun_img, xmin = 21, xmax = 26, ymin = 24, ymax = 29) +

  # Plot formatting
  xlab("Elapsed Time (h)") + 
  ylab("Soil Temperature (C)") +
  theme_bw() +
  theme(text = element_text(size = 15),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank()) +
  scale_x_continuous(limits = c(0, 48))

soiltemp_m2_p1

# save the plot
ggsave(filename = 
       here("output","figures", "microphase2_soiltemp_plot.jpg"),
       device = "jpeg",
       width = 8, height = 6, dpi = 300)

```

```{r}
#| label: soil+air temperature plot (Fig. 4B)

soil_and_air_temp_m2_p1 <- weather_phase2_gob_df |>
  ggplot(aes(x = elapsed_time)) +
  # Add shaded night areas
  annotate("rect", xmin = night1_start_m2, xmax = night1_end_m2, 
           ymin = -Inf, ymax = Inf, alpha = 0.2, fill = "grey") +
  annotate("rect", xmin = night2_start_m2, xmax = night2_end_m2, 
           ymin = -Inf, ymax = Inf, alpha = 0.2, fill = "grey") +
  
  # Add soil temperature (brown dashed) and air temperature (blue solid) lines
  geom_line(aes(y = SoilTemp, color = "Soil Temperature"), 
            linetype = "dashed", linewidth = 1) +
  geom_line(aes(y = AirTemp, color = "Air Temperature"), linewidth = 1) +
  # Add moon images
  annotation_custom(moon_img, xmin = 11, xmax = 15, ymin = 25, ymax = 29) +
  annotation_custom(moon_img, xmin = 35, xmax = 39, ymin = 25, ymax = 29) +

  # Add sun images in day areas
  annotation_custom(sun_img, xmin = 23, xmax = 27, ymin = 25, ymax = 29) +
 # annotation_custom(sun_img, xmin = 39, xmax = 41, ymin = 30, ymax = 36) +

  # Add "B." in upper-left corner
  annotate("text", x = 0, y = Inf, label = "B.", hjust = -0.5, 
           vjust = 1.5, size = 6) +

  # Axes and scales
  scale_color_manual(values = c("Soil Temperature" = "#6e4424", "Air Temperature" = "blue")) +
  scale_x_continuous(limits = c(0, 48), expand = c(0, 0)) +
  scale_y_continuous(limits = c(0, 30), expand = c(0, 0)) +
  xlab("Elapsed Time (hours)") + 
  ylab("Temperature (°C)") +
  
  # Theme tweaks
  theme_bw() +
  theme(
    text = element_text(size = 15),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    legend.position = c(0.85, 0.70),
    legend.justification = c("right", "top"),
    legend.background = element_blank(),
    legend.key = element_blank(),
    legend.title = element_blank(),
    legend.text = element_text(size = 12)
  )

soil_and_air_temp_m2_p1

# save the plot
ggsave(filename = 
       here("output","figures", "Fig4B_microphase2_soil_and_air_temp_plot.jpg"),
       device = "jpeg",
       width = 8, height = 6, dpi = 300)
```

```{r}
#| label: Combine plots (FIG 4)

# supress legends in plot 2, use plot 1 legends for combined plot
plotC <- fog_humidity_m2_p1 + theme(legend.position = "none")
plotD <- soil_and_air_temp_m2_p1 + theme(legend.position = c(0.92, 0.75))

combined_plots <- plot_grid(plotC, plotD, ncol = 1, align = "v", rel_heights = c(1, 1))

final_plot <- ggdraw() +
  draw_plot(combined_plots, x = 0, y = 0, width = 1, height = 1)
final_plot

# save the plot
ggsave(filename = 
       here("output","figures", "Fig4_microphase2_weather.jpg"),
       device = "jpeg",
       width = 8, height = 6, dpi = 300)
```
